name: Java CI on Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master    
      
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        java-package: jdk
        architecture: x64
        check-latest: false
        server-id: github
        server-username: ${{ github.actor }}
        server-password: ${{ github.token }}
        overwrite-settings: true
        job-status: success

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn test -e -X

