name: Java CI

on:
  push:
    branches:
      - main # Run workflow on changes in the main branch
  pull_request:
    branches:
      - main # Run on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install
